# Generated by Django 5.2.4 on 2025-08-05 21:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('passing_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('exam_type', models.CharField(choices=[('standard', 'Standard'), ('adaptive', 'Adaptive'), ('timed', 'Timed')], default='standard', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('proctoring_enabled', models.BooleanField(default=True)),
                ('ai_monitoring_level', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('strict', 'Strict')], default='standard', max_length=50)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('code', 'Code'), ('image_based', 'Image-Based'), ('audio_based', 'Audio-Based')], max_length=50)),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('order_index', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('media_urls', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
            ],
        ),
        migrations.CreateModel(
            name='ExamProctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('active', 'Active'), ('completed', 'Completed'), ('removed', 'Removed')], default='assigned', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigner', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('proctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_proctor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exam', 'proctor')},
            },
        ),
    ]
